### ISSUE TITLE
Information Gathering and Project Management

### ISSUE THREAD

**Issue by AvinashTgk** [AvinashTgk/ASE-Team-Project#5]

**Comment by SaiTejasweeReddy** [comment]
i am now attaching documentation which is yet to be worked on...
[first_increment.docx](https://github.com/AvinashTgk/ASE-Team-Project/files/784680/first_increment.docx)

**Comment by SaiTejasweeReddy** [comment]
i chose this as our project icon
Please review
![medianizer](https://cloud.githubusercontent.com/assets/25338189/23089197/fa7d8a70-f54a-11e6-84b7-55a4b3a9db27.png)

**Comment by SaiTejasweeReddy** [comment]
this is a pie chart depicting the contribution of our team members as per your instructions
![project_contribution](https://cloud.githubusercontent.com/assets/25338189/23089237/7358e016-f54b-11e6-9ee2-35c2205b923b.PNG)

**Comment by SaiTejasweeReddy** [comment]
can you please assign the writing of user stories to one of the other teammates if possible

**Comment by SaiTejasweeReddy** [comment]
Please send me the screenshots so that i can put them in the documentation

**Comment by AvinashTgk** [comment]
Yes sure I will

**Comment by SaiTejasweeReddy** [comment]
this is the final document for first increment of our project
[ASE project first increment1.docx](https://github.com/AvinashTgk/ASE-Team-Project/files/784798/ASE.project.first.increment1.docx)

**Comment by SaiTejasweeReddy** [comment]
there is a search api that we could use for our app
i am mailing you the same
